USE CraftStoreDB_QA;

DECLARE @InventoryID int;
DECLARE @ProductTypeID int = 1;
DECLARE @Description nvarchar(50)= 'inventory description';
DECLARE @Material nvarchar(50) = 'inventory material';
DECLARE @Size nvarchar(50) = 1;
DECLARE @Color nvarchar(5) = 'inventory color';
DECLARE @ListPrice money = 1.00;
DECLARE @ProductionCost money = 1.00;
DECLARE @MadeOn date = '1900-01-01';
DECLARE @PictureURL nvarchar(50) = 'inventory url';

BEGIN TRANSACTION;

INSERT INTO [dbo].[Inventory]
  ([ProductTypeID],[Description],[Material],[Size],[Color],[ListPrice],[ProductionCost],[MadeOn],[PictureURL])
     VALUES
			(@ProductTypeID,@Description,@Material,@Size,@Color,@ListPrice,@ProductionCost,@MadeOn,@PictureURL);
			-- capture autogenerated identity PK as StockORder ID
	SELECT @InventoryID = SCOPE_IDENTITY();
	COMMIT TRANSACTION;
	SELECT @InventoryID AS InventoryID;

GO
