-- =============================================
-- Author:		<Justin Pittman>
-- Create date: <Oct 13, 2017>
-- Description:	stored procedure for new inventory being made
-- =============================================

--
-- setup
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

USE CraftStoreDB_QA;

DECLARE @InventoryID int;

IF EXISTS (SELECT 1 FROM sys.procedures	WHERE [name] = 'InsertInventory')
	BEGIN
		DROP PROCEDURE dbo.InsertInventory;
	END;
GO

CREATE PROCEDURE dbo.InsertInventory 
	-- Add the parameters for the stored procedure here
	(
	@InventoryID INT = 0 OUTPUT,
	@ProductTypeID int = 1,
	@Description nvarchar(50)= 'inventory description',
	@Material nvarchar(50) = 'inventory material',
	@Size nvarchar(50) = 1,
	@Color nvarchar(5) = 'inventory color',
	@ListPrice money = 1.00,
	@ProductionCost money = 1.00,
	@MadeOn date = '1900-01-01',
	@PictureURL nvarchar(50) = 'inventory url'
	)
AS
BEGIN
	-- count rows affected
	SET NOCOUNT OFF;
	-- Best practice to wrap an insert into a transaction block
	BEGIN TRANSACTION;
		INSERT INTO [dbo].[Inventory]([ProductTypeID],[Description],[Material],[Size],[Color],[ListPrice],[ProductionCost],[MadeOn],[PictureURL])
		VALUES (@ProductTypeID,@Description,@Material,@Size,@Color,@ListPrice,@ProductionCost,@MadeOn,@PictureURL);
			-- capture autogenerated identity PK as StockORder ID
		SELECT @InventoryID = SCOPE_IDENTITY();
	COMMIT TRANSACTION;
	SELECT @InventoryID AS InventoryID;
END;
GO
