USE CraftStoreDB_QA;

DECLARE @StockOrderID int;
DECLARE @CustomerID int = 1;
DECLARE @InventoryID int = 1;
DECLARE	@Quantity smallint = 1;
DECLARE @Time smalldatetime = '2007-05-08 12:35:00';
DECLARE	@Paid bit = 1;
DECLARE	@SellPrice money = 1.00;

BEGIN TRANSACTION;

INSERT INTO [dbo].[StockOrder]
           ([CustomerID] ,[InventoryID], [Quantity], [Time], [Paid], [SellPrice])
     VALUES
			(@CustomerID, @InventoryID,	@Quantity, @Time, @Paid, @SellPrice);

			-- capture autogenerated identity PK as StockORder ID
	SELECT @StockOrderID = SCOPE_IDENTITY();
		
	COMMIT TRANSACTION;

GO
