- name: playbook to deploy new VM
  hosts: localhost
  gather_facts: yes
  become: no
  vars:
    pool_dir: "/home/jupittma/VirtualMachines"
    vm: rhel8-5
    vcpus: 2
    ram_mb: 2048
    cleanup: no
    net: default
    ssh_pub_key: "/home/jupittma/.ssh/id_rsa.pub"
  tasks:
    - name: call role to provision via KVM
      include_role:
        name: kvm_provision
      vars:
        libvirt_pool_dir: "{{ pool_dir }}"
        vm_name: "{{ vm }}"
        vm_vcpus: "{{ vcpus }}"
        vm_ram_mb: "{{ ram_mb }}"
        vm_net: "{{ net }}"
        cleanup_tmp: "{{ cleanup }}"
        ssh_key: "{{ ssh_pub_key }}"
