apiVersion: v1
items:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: "2020-03-09T20:18:36Z"
    generation: 2
    labels:
      app: sample-php
    name: sample-php
    namespace: 65de-exploring-openshift
    resourceVersion: "321255605"
    selfLink: /apis/apps.openshift.io/v1/namespaces/65de-exploring-openshift/deploymentconfigs/sample-php
    uid: 28115d29-6243-11ea-83d6-0a580a8201e2
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: sample-php
      deploymentconfig: sample-php
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: sample-php
          deploymentconfig: sample-php
      spec:
        containers:
        - image: image-registry.openshift-image-registry.svc:5000/65de-exploring-openshift/sample-php@sha256:7a84ccbd386a1116b337e70d98db9d3856eccb69990ef1c82a89f9da00d0c7fb
          imagePullPolicy: Always
          name: sample-php
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - sample-php
        from:
          kind: ImageStreamTag
          name: sample-php:latest
          namespace: 65de-exploring-openshift
        lastTriggeredImage: image-registry.openshift-image-registry.svc:5000/65de-exploring-openshift/sample-php@sha256:7a84ccbd386a1116b337e70d98db9d3856eccb69990ef1c82a89f9da00d0c7fb
      type: ImageChange
    - type: ConfigChange
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2020-03-09T20:22:05Z"
      lastUpdateTime: "2020-03-09T20:22:05Z"
      message: Deployment config has minimum availability.
      status: "True"
      type: Available
    - lastTransitionTime: "2020-03-09T20:22:06Z"
      lastUpdateTime: "2020-03-09T20:22:06Z"
      message: replication controller "sample-php-1" successfully rolled out
      reason: NewReplicationControllerAvailable
      status: "True"
      type: Progressing
    details:
      causes:
      - type: ConfigChange
      message: config change
    latestVersion: 1
    observedGeneration: 2
    readyReplicas: 1
    replicas: 1
    unavailableReplicas: 0
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
